FROM python:3.8-slim

# root project dir is named 'app'
# inside root dir is dir named 'app'
# that contains server entry file 'main'
COPY ./app /app/app
COPY ./__init__.py /app
COPY ./private.py /app
COPY ./other_ops/topics.py app/other_ops/topics.py

RUN pip install -r app/app/requirements.txt

EXPOSE 80
CMD cd app && uvicorn app.main:app --host 0.0.0.0 --port 80