
topics = {
    'GME': {'gme', 'gamestop', 'gamestonk'},
    'AMC': {'amc'},
    'PLTR': {'pltr', 'palantir'},
    'SPY': {'spy'},
    'DOGE': {'dogecoin'},
    'crypto': {'coin', 'cypto', 'mining'},
    'UVXY': {'uvxy'},
    'SDOW': {'sdow'},
    'SQQQ': {'sqqq'},
    'SRTY': {'srty'},
    'WSB': {'wsb'},

    'GOOGL': {'googl'},
    'AMZN': {'amzn'},
    'AAPL': {'aapl'},
    'NFLX': {'nflx'},
    'MSFT': {'msft'},
    'TSLA': {'tsla'},
    'NVDA': {'nvda'},
    'TECH': {'tech'},
    'INTC': {'intc'},
    'BABA': {'baba'},
    'PYPL': {'pypl'},
    'CSCO': {'csco'},
    'MTCH': {'mtch'},
    'ADBE': {'adbe'},
    'DBX': {'dbx'},
    'QQQ': {'qqq'},
    'CRM': {'crm'}
}
